// message template collection
export const REQUEST_MESSAGE_TEMPLATES_START = 'REQUEST_MESSAGE_TEMPLATES_START';
export const REQUEST_MESSAGE_TEMPLATES_ERROR = 'REQUEST_MESSAGE_TEMPLATES_ERROR';
export const REQUEST_MESSAGE_TEMPLATES_SUCCESS = 'REQUEST_MESSAGE_TEMPLATES_SUCCESS';

// one message tempate
export const REQUEST_MESSAGE_TEMPLATE_START = 'REQUEST_MESSAGE_TEMPLATE_START';
export const REQUEST_MESSAGE_TEMPLATE_ERROR = 'REQUEST_MESSAGE_TEMPLATE_ERROR';
export const REQUEST_MESSAGE_TEMPLATE_SUCCESS = 'REQUEST_MESSAGE_TEMPLATE_SUCCESS';

export const UPDATE_MESSAGE_TEMPLATE_START = 'UPDATE_MESSAGE_TEMPLATE_START';
export const UPDATE_MESSAGE_TEMPLATE_ERROR = 'UPDATE_MESSAGE_TEMPLATE_ERROR';
export const UPDATE_MESSAGE_TEMPLATE_SUCCESS = 'UPDATE_MESSAGE_TEMPLATE_SUCCESS';

export const CREATE_MESSAGE_TEMPLATE_START = 'CREATE_MESSAGE_TEMPLATE_START';
export const CREATE_MESSAGE_TEMPLATE_ERROR = 'CREATE_MESSAGE_TEMPLATE_ERROR';
export const CREATE_MESSAGE_TEMPLATE_SUCCESS = 'CREATE_MESSAGE_TEMPLATE_SUCCESS';

export const DELETE_MESSAGE_TEMPLATE_START = 'DELETE_MESSAGE_TEMPLATE_START';
export const DELETE_MESSAGE_TEMPLATE_ERROR = 'DELETE_MESSAGE_TEMPLATE_ERROR';
export const DELETE_MESSAGE_TEMPLATE_SUCCESS = 'DELETE_MESSAGE_TEMPLATE_SUCCESS';

export const APPLY_MESSAGE_TEMPLATE = 'APPLY_MESSAGE_TEMPLATE';

// folders
export const REQUEST_ORDERS_FOLDERS_START = 'REQUEST_ORDERS_FOLDERS_START';
export const REQUEST_ORDERS_FOLDERS_ERROR = 'REQUEST_ORDERS_FOLDERS_ERROR ';
export const REQUEST_ORDERS_FOLDERS_SUCCESS = 'REQUEST_ORDERS_FOLDERS_SUCCESS';
